### ISSUE TITLE
Hg19 integration?

### ISSUE THREAD

**Issue by mkinnaman** [andrewSharo/StrVCTVRE#1]
Lot of potential with this tool!

WIll you be rolling out a version that works with HG19 genomes?

Thanks,
MIchael

**Comment by andrewSharo** [comment]
Hi Michael,

Thanks for your interest in StrVCTVRE! I'm happy to include an option for hg19. If you're going to be working with a lot of SV data, I do recommend considering the switch to hg38. It's a better build for SV detection and most major databases now support hg38. 

As you're likely already aware, you can also use the UCSC liftover tool (https://genome.ucsc.edu/cgi-bin/hgLiftOver) in the mean time to convert from hg19 to hg38. This will however not work for all SVs, so it's not a perfect solution. I'll reply to this message when I release a hg19 version so you're updated right away.

Best, Andrew

**Comment by andrewSharo** [comment]
StrVCTVRE can now annotate SVs in hg19/GRCh37 coordinates.
