### ISSUE TITLE
Can't run example

### ISSUE THREAD

**Issue by Gedofs** [andrewSharo/StrVCTVRE#4]
Hi! I can't currently run example. Terminal keeps printing this every time I run example : "intersectBed" does not
appear to be installed or on the path, so this method is disabled.
Please install a more recent version of BEDTools and re-import to use this method"

Is there a way I can fix this? Hope you can help me! thanks

<img width="1372" alt="Screen Shot 2022-06-28 at 11 56 52" src="https://user-images.githubusercontent.com/94254364/176238188-eeb8d60d-3697-4364-8ef2-ee6c746243be.png">
e

**Comment by andrewSharo** [comment]
Hi Gerardo,
When you run 
`bedtools --version`
in your terminal, what does it give you? It looks like you may need to install bedtools or update to a newer version.

**Comment by Gedofs** [comment]
It prints "command not found", though I've already installed both bedtools.static.binary and bedtools2 folder (version 2.30.0) and moved them to Applications folder. 

I wonder if I can move them to another directory

**Comment by Gedofs** [comment]
By the way, I could not install pybedtools, cyvcf2 and pybigwig using bioconda. I have to install them using pip.

**Comment by andrewSharo** [comment]
Hi Gerardo,
You may want to check if the bedtools binaries are in a directory that is in your PATH. Otherwise, you may want to update your PATH variable to include the bedtools directory. I am not a Mac person, so I can only provide limited help, but you may find this helpful: https://www.cyberciti.biz/faq/appleosx-bash-unix-change-set-path-environment-variable/

**Comment by andrewSharo** [comment]
If you are unable to get it running, you can also try uploading your variants to our job submission site: https://strvctvre.berkeley.edu/annotate.html

**Comment by Gedofs** [comment]
thanks! I tried to upload my variants before but my file is 4Kb

**Comment by Gedofs** [comment]
Seems that the web version only calls for variants in chromosome 1.

![image](https://user-images.githubusercontent.com/94254364/176280938-4d084d40-9e11-4f3f-aba5-588433a8e680.png)

By the way! I could already install Bedtools but now there is a new problem...
<img width="1126" alt="Screen Shot 2022-06-28 at 15 10 58" src="https://user-images.githubusercontent.com/94254364/176281674-0b59b3c2-5a29-46c1-93fc-8f9863d29968.png">

**Comment by andrewSharo** [comment]
You will need to use 'chr1','chr2','chr3',etc or 1,2,3,etc as the chromosome names in your vcf file. Then the web version should be able to call your variants. 4kb should be no problem for uploading. 
I am not familiar with the new error you are getting. Can you paste the text of the error, rather than a screenshot?

**Comment by Gedofs** [comment]
Thanks! Here is the text:

/Users/gerardo/StrVCTVRE/annotationFinalForStrVCTVRE.py:137:
VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences
(which is a list-or-tuple of lists-or-tuples-or ndarrays with different
lengths or shapes) is deprecated. If you meant to do this, you must specify
'dtype=object' when creating the ndarray.

  x = np.asarray(x)

Traceback (most recent call last):

  File "/Users/gerardo/StrVCTVRE/test_StrVCTVRE.py", line 166, in <module>

    rf = load('data/rfTrainedAllChromsExcept'+chrm+'.joblib')

  File
"/Users/gerardo/opt/anaconda3/lib/python3.9/site-packages/joblib/numpy_pickle.py",
line 587, in load

    obj = _unpickle(fobj, filename, mmap_mode)

  File
"/Users/gerardo/opt/anaconda3/lib/python3.9/site-packages/joblib/numpy_pickle.py",
line 506, in _unpickle

    obj = unpickler.load()

  File "/Users/gerardo/opt/anaconda3/lib/python3.9/pickle.py", line 1212,
in load

    dispatch[key[0]](self)

  File "/Users/gerardo/opt/anaconda3/lib/python3.9/pickle.py", line 1528,
in load_global

    klass = self.find_class(module, name)

  File "/Users/gerardo/opt/anaconda3/lib/python3.9/pickle.py", line 1579,
in find_class

    __import__(module, level=0)

  File
"/Users/gerardo/opt/anaconda3/lib/python3.9/site-packages/sklearn/__init__.py",
line 82, in <module>

    from .base import clone

  File
"/Users/gerardo/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py",
line 17, in <module>

    from .utils import _IS_32BIT

  File
"/Users/gerardo/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/__init__.py",
line 29, in <module>

    from .fixes import parse_version, threadpool_info

  File
"/Users/gerardo/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/fixes.py",
line 19, in <module>

    import scipy.stats

  File
"/Users/gerardo/opt/anaconda3/lib/python3.9/site-packages/scipy/stats/__init__.py",
line 453, in <module>

    from ._stats_py import *

  File
"/Users/gerardo/opt/anaconda3/lib/python3.9/site-packages/scipy/stats/_stats_py.py",
line 38, in <module>

    from scipy.spatial.distance import cdist

  File
"/Users/gerardo/opt/anaconda3/lib/python3.9/site-packages/scipy/spatial/__init__.py",
line 104, in <module>

    from ._qhull import *

ImportError:
dlopen(/Users/gerardo/opt/anaconda3/lib/python3.9/site-packages/scipy/spatial/_
qhull.cpython-39-darwin.so, 0x0002): Library not loaded:
@rpath/liblapack.3.dylib

  Referenced from:
/Users/gerardo/opt/anaconda3/lib/python3.9/site-packages/scipy/spatial/_
qhull.cpython-39-darwin.so
  Reason: tried:
'/Users/gerardo/opt/anaconda3/lib/python3.9/site-packages/scipy/spatial/../../../../liblapack.3.dylib'
(no such file),
'/Users/gerardo/opt/anaconda3/lib/python3.9/site-packages/scipy/spatial/../../../../liblapack.3.dylib'
(no such file), '/Users/gerardo/opt/anaconda3/bin/../lib/liblapack.3.dylib'
(no such file), '/Users/gerardo/opt/anaconda3/bin/../lib/liblapack.3.dylib'
(no such file), '/usr/local/lib/liblapack.3.dylib' (no such file),
'/usr/lib/liblapack.3.dylib' (no such file)

**Comment by andrewSharo** [comment]
Hi Gerardo,
Sorry for my delay in getting back to you. It looks like you're using a version of numpy that is incompatible with StrVCTVRE. Were you able to build a conda environment using the yml file? (https://github.com/andrewSharo/StrVCTVRE/blob/master/environment_py2.7.yml). StrVCTVRE requires numpy version 1.16.5. I would recommend that you use the yml file to create a custom conda environment for StrVCTVRE. Otherwise, you are likely to run into a lot of version incompatibility issues. See step 4 of the readme for more info.

--Andrew

**Comment by Gedofs** [comment]
Thanks for your answer. I had no problem when building conda environment,
though i still cant run structure from terminal. After all, I was able to
run the web version and here is part of the result. Seems like it worked,
what do you think?[image: image.png]

**Comment by andrewSharo** [comment]
Hi Gerardo,
Sorry for my slow reply. I'm not able to see the image, but I expect the web version did work. Feel free to re-open this if you have further issues.
--Andrew
