### ISSUE TITLE
Recommendations for using pathogenic score

### ISSUE THREAD

**Issue by akhilpampana** [andrewSharo/StrVCTVRE#5]
Hello, 

Thank you for the nice package developed. I have a question. I am doing annotations for WGS SV dataset for a set of genes and would like to use the scores for further analysis. What are your recommendations for identifying and annotating putative pathogenic structural variants based on the score given by the package? I have gone through your paper and couldn't able to find any recommendations so thought of reaching out to you here. It would be of real help if you could able to let me know the recommendations. 

Thank you for the help.

Regards
Akhil

**Comment by andrewSharo** [comment]
Hi Akhil,

Thanks for reaching out! We considered putting thresholds in the manuscript, but it is difficult to validate thresholds. We instead recommend that users give greater attention to SVs with higher StrVCTVRE scores. However, I do understand that sometimes thresholds are necessary. We empirically found that 90% of pathogenic SVs are identified when using a StrVCTVRE score of 0.37 or greater. So if a 90% sensitivity is acceptable, you could remove from consideration those SVs with a StrVCTVRE score less than 0.37. We also found the following thresholds to be generally correct, but could not rigorously validate them: SVs with a StrVCTVRE score greater than 0.77 were 2.1 times more likely to be pathogenic than benign. SVs with a StrVCTVRE score greater than 0.82 were 4.3 times more likely to be pathogenic than benign. Again, these thresholds are estimates and may not be accurate depending on your data. Does this answer your question?

Best, 
Andrew

**Comment by akhilpampana** [comment]
Yes, It answered my question partially.  I will check with my PI regarding what's the value we can use.  How did you do the sensitivity analysis? Do you have a set of steps that I can try within our dataset and find a value that suits my data?

**Comment by andrewSharo** [comment]
The sensitivity analysis was done on datasets containing SVs that were known/labeled as pathogenic or benign. If you have a dataset with a large number of known pathogenic and benign variants, then you can create an ROC curve for StrVCTVRE scores and derive your 90% sensitivity threshold from that. Let me know if you need more info

**Comment by andrewSharo** [comment]
I'm going to close this due to inactivity, but feel free to re-open if you have questions.
