### ISSUE TITLE
Getting an ERROR from test_StrVCTVRE.py

### ISSUE THREAD

**Issue by projectoriented** [andrewSharo/StrVCTVRE#6]
Hello 👋 ,

Thank you for developing the package. I'm getting an error when I execute `test_StrVCTVRE.py -p data/hg38.phyloP100way.bw`

```
reading VCF...


formatting VCF data...


identifying exonic deletions and duplications...


scoring exonic deletions and duplications...


writing annotated VCF...

ERROR: StrVCTVRE is not running correctly
```
It produces `data/test.annotated.vcf.gz` and is the same size as `data/test.correctAnnotation.vcf.gz`. I'm running on `python 2.7.15` and have installed everything available through `pip install`. Any help would be appreciated, thanks!

**Comment by andrewSharo** [comment]
Hi Mei,

Thanks for your interest in StrVCTVRE! It's possible I forgot to update the test.correctAnnotation.vcf.gz file. I'll look into this today. How did you download StrVCTVRE? Did you use git or did you download the tar.gz file?

--Andrew

**Comment by projectoriented** [comment]
I downloaded the tarball from your latest release v1.7

**Comment by andrewSharo** [comment]
Hi Mei,

Thanks for bringing this bug to my attention. I wasn't able to reproduce the error when I downloaded the v.1.7 tarball. I've created a new release v.1.8 but I'm not sure if that will help. Before you download the new tarball, can you try the following:

The error that you're reporting indicates that there is some difference between data/test.annotated.vcf.gz and data/test.correctAnnotation.vcf.gz files. Can you try running 
`diff data/test.annotated.vcf.gz data/test.annotated.vcf.gz`
and see if it indicates any difference? 
Depending on your version of diff, you may need to run 
`diff <(zcat data/test.annotated.vcf.gz) <(zcat data/test.correctAnnotation.vcf.gz)`
If diff gives no output, it means the files are identical and StrVCTVRE is working properly. If diff gives output, can you upload the data/test.annotated.vcf.gz and data/test.correctAnnotation.vcf.gz so I can see what's different?

--Andrew

**Comment by projectoriented** [comment]
I used `diff` on both releases after running the tests and there was no output. It may have something to do with the binaries installed outside of pip. In any case, StrVCTVRE is working properly despite the error message 😄 . Thank you for your prompt responses!
